//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace SameOldStory.Input.Unity
{
    public partial class @UnityInputSystem : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @UnityInputSystem()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""Studio"",
            ""id"": ""f648c785-05c9-4593-a490-1179ea343752"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""4702443c-75d0-4b8f-bb7c-5e2fbc03863e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5ce579bf-e802-406e-bc0a-012324ccbfcf"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Studio
            m_Studio = asset.FindActionMap("Studio", throwIfNotFound: true);
            m_Studio_MousePosition = m_Studio.FindAction("MousePosition", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Studio
        private readonly InputActionMap m_Studio;
        private IStudioActions m_StudioActionsCallbackInterface;
        private readonly InputAction m_Studio_MousePosition;
        public struct StudioActions
        {
            private @UnityInputSystem m_Wrapper;
            public StudioActions(@UnityInputSystem wrapper) { m_Wrapper = wrapper; }
            public InputAction @MousePosition => m_Wrapper.m_Studio_MousePosition;
            public InputActionMap Get() { return m_Wrapper.m_Studio; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(StudioActions set) { return set.Get(); }
            public void SetCallbacks(IStudioActions instance)
            {
                if (m_Wrapper.m_StudioActionsCallbackInterface != null)
                {
                    @MousePosition.started -= m_Wrapper.m_StudioActionsCallbackInterface.OnMousePosition;
                    @MousePosition.performed -= m_Wrapper.m_StudioActionsCallbackInterface.OnMousePosition;
                    @MousePosition.canceled -= m_Wrapper.m_StudioActionsCallbackInterface.OnMousePosition;
                }
                m_Wrapper.m_StudioActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @MousePosition.started += instance.OnMousePosition;
                    @MousePosition.performed += instance.OnMousePosition;
                    @MousePosition.canceled += instance.OnMousePosition;
                }
            }
        }
        public StudioActions @Studio => new StudioActions(this);
        public interface IStudioActions
        {
            void OnMousePosition(InputAction.CallbackContext context);
        }
    }
}
